url: http://www.jamiekurtz.com
baseurl:
paginate: 10
paginate_path: "/blog/page:num/"

# Site settings
title: Jamie Kurtz | Solutions Architect
email: jamie@jamiekurtz.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."

# Color settings (hex-codes without the leading hash-tag)
#3B6DA5 -- blue
#FD794C -- orange
#FDDC4C -- yellow
#FDB74C -- yellow-orange

#Created from lightbulb pic:
# 3B6DA5 - blue
# F5D494 - light yellow
# DFD9D6 - light gray
# A56C36 - brown
# 3F3F41 - blackish
#
color:
  primary: 3B6DA5
  secondary: F5D494
  secondary-dark: A56C36

# Publications
publications:
- title: "ASP.NET MVC 4 and the Web API: Building a REST Service from Start to Finish"
  date: January 2013
  url: "http://www.amazon.com/Using-ASP-NET-Web-API-MVC/dp/1430249773"
  pic: mvc-webapi-thumb
  description: If you’re new to the REST architecture and/or new to ASP.NET Web API, this book will help you learn both in a short amount of time. I take you quickly through the basics of HTTP REST, some of the more prominent features in Web API, setting up a simple Web API solution in Visual Studio, and securing the service – all within just a little over 100 pages.

- title: Pro Drupal as an Enterprise Development Platform
  date: November 2013
  url: "http://www.amazon.com/Pro-Drupal-Enterprise-Development-Platform/dp/1430260041"
  pic: ent-drupal-thumb
  description: "Are you a developer or IT manager that has ever thought there has to be a better/faster/cheaper way? Rather than continuing to write the same code and components over and over, this book can help you start with a solid, “mostly-there” platform, allowing you to focus on filling the business-specific gaps that actually change from project to project. "

- title: "ASP.NET Web API 2: Building a REST Service from Start to Finish"
  date: July 2014
  url: "http://www.amazon.com/ASP-NET-Web-API-Building-Service/dp/1484201108"
  pic: webapi2-thumb
  description: "Following on the heels of my first MVC/WebAPI book, Brian Wortman and I set out to address some of the concerns and feedback I received with regards to a lack of focus on the underlying Web API framework. This new edition focuses more on the Web API, includes more content related to testing, and a working Single Page Application web site that uses the REST service built throughout the book. We think you’ll find this book filled with lots more information, with a big increase in focus."

- title: "REST Services with ASP.NET Web API – SVNUG Presentation"
  date: May 2013
  url: "http://youtu.be/5AGuE_hAmzk?t=1m35s"
  pic: jamiekurtz-svnug-thumb
  description: "Video of me presenting “REST Services with ASP.NET Web API” to the Sangamon Valley .NET User Group (SVNUG), downtown Springfield, Illinois."

- title: "Online JSON Web Token Builder"
  date:
  url: "http://jwtbuilder.jamiekurtz.com/"
  pic: jwt-builder
  description: "A simple online JSON Web Token (JWT) builder, where you can specify your claims and signing algorithm, and it creates a working JWT."

- title: "Various Nuget Packages"
  date:
  url: "https://www.nuget.org/packages?q=%22Jamie+Kurtz%22"
  pic: NuGet-Logo-2
  description: "Some .NET Framework open source packages I've published to Nuget.org, mostly dealing with web site and API security."


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jakurtz
  - title: linkedin
    url: https://www.linkedin.com/pub/jamie-kurtz/1a/658/bb9
  - title: github
    url: http://github.com/jamiekurtz

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty